version: '3'

services: 

    backend:
        build: ./backend
        expose:
            - 3001
        ports:
            - "3001:3001" # Map for now
        links:
            - postgres:postgres
        env_file: .env
        command: node server.js
    
    client:
        build: ./client
        expose:
            - 3000
        ports:
            - "3000:3000" # Map for now
        links:
            - backend:backend
        command: serve -s build -p 3000
    
    postgres:
        build: ./postgres
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust # TEMP SOLUTION
        expose:
            - 5432